[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft_anchor = "AKCBYwLir3q8LfJAeCHX6r2sguYFKtT3ZiuGWGFwpvZ5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
